import { StyleSheet } from "react-native";

const DestinationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5", padding: 20 },
  headerContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 30, paddingTop: 25, paddingBottom: 20 },
  sideBarButton: { backgroundColor: '#E0E0E0', width: 45, height: 45, borderRadius: 22.5, justifyContent: 'center', alignItems: 'center' },
  sideBarImage: { width: 45, height: 45, resizeMode: 'contain' },
  logo: { width: 60, height: 60, resizeMode: 'contain' },
  rightIconsContainer: { flexDirection: 'row', alignItems: 'center', position: 'relative' },
  profileIcon: { width: 45, height: 45, borderRadius: 22.5 },
  bellButton: { position: 'absolute', top: -5, left: -10, zIndex: 1 },
  bellIcon: { width: 25, height: 25 },
  heroTitle: { fontSize: 22, fontWeight: "700", color: "#305797", textAlign: "center", marginTop: 10 },
  heroSubtitle: { fontSize: 12, color: "#777", textAlign: "center", marginTop: 4, marginBottom: 16 },
  searchRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  searchBar: { flex: 1, flexDirection: "row", alignItems: "center", backgroundColor: "#fff", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: "#dbe3ef" },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: "#333" },
  filterButton: { flexDirection: "row", alignItems: "center", backgroundColor: "#305797", borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, elevation: 2 },
  filterButtonText: { color: "#fff", fontWeight: "600", fontSize: 14, marginLeft: 6 },
  resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 15, marginTop: 5 },
  resultsTitle: { fontSize: 18, fontWeight: "700", color: "#1e293b" },
  resultsCount: { fontSize: 12, color: "#94a3b8" },
  packageCard: { backgroundColor: "#fff", borderRadius: 16, marginBottom: 18, elevation: 3, overflow: "hidden", borderWidth: 1, borderColor: "#e6e9ef" },
  packageImage: { width: "100%", height: 180 },
  packageContent: { padding: 16 },
  cardHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  packageTitle: { fontSize: 16, fontWeight: "700", color: "#1e293b", flex: 1, marginRight: 10 },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  ratingText: { fontSize: 13, fontWeight: '700', color: '#fbbf24' },
  cardSubHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  typeTag: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  typeTagText: { fontSize: 10, fontWeight: "700" },
  availTag: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  availTagText: { fontSize: 10, fontWeight: "700" },
  durationText: { fontSize: 13, color: "#64748b" },
  slotsText: { fontSize: 14, color: "#94a3b8", marginBottom: 10, marginTop: 2 },
  packageTagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  tagPill: { backgroundColor: "#e6f4ff", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, borderColor: "#91caff" },
  tagText: { fontSize: 10, color: "#1677ff" },
  packageFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#f0f0f0" },
  priceContainer: { flex: 1 },
  priceRowBox: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  packagePrice: { fontSize: 18, fontWeight: "700", color: "#1e293b" },
  budgetPaxText: { fontSize: 11, color: "#94a3b8" },
  viewDetailsButton: { backgroundColor: "#305797", paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  viewDetailsText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  detailsContainer: { flex: 1, backgroundColor: "#fff" },
  detailsHeader: { paddingHorizontal: 16 },
  titleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 },
  detailsTitle: { fontSize: 20, fontWeight: "700", color: "#305797" },
  daysBadge: { backgroundColor: "#305797", borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6 },
  daysText: { color: "#fff", fontWeight: "700", fontSize: 11, textAlign: "center" },
  heroImage: { width: "100%", height: 200, borderRadius: 12, marginTop: 10 },
  heroCard: { backgroundColor: "#fff", borderRadius: 14, elevation: 3, marginTop: -20, marginHorizontal: 16, padding: 12, borderWidth: 1, borderColor: "#e6e9ef" },
  heroDescription: { fontSize: 12, color: "#777", textAlign: "center" },
  priceRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12 },
  priceLabel: { fontSize: 11, color: "#777" },
  priceValue: { fontSize: 22, fontWeight: "700", color: "#305797" },
  priceUnit: { fontSize: 11, color: "#777" },
  availabilityButton: { backgroundColor: "#305797", paddingHorizontal: 16, paddingVertical: 8, borderRadius: 16 },
  availabilityText: { color: "#fff", fontWeight: "600", fontSize: 11 },

  // 🔥 UPDATED TAB STYLES 🔥
  tabRow: { flexDirection: "row", backgroundColor: "#305797", marginTop: 20, padding: 0 },
  tabButton: { flex: 1, paddingVertical: 10, alignItems: "center" },
  tabButtonActive: { backgroundColor: "#fff" },
  tabText: { color: "#fff", fontSize: 13, fontFamily: "Montserrat_600SemiBold" },
  tabTextActive: { color: "#305797", fontFamily: "Montserrat_700Bold" },

  sectionBody: { padding: 16, paddingBottom: 120 },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#305797", marginBottom: 6 },
  sectionText: { fontSize: 12, color: "#333", lineHeight: 18 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
  modalCard: { backgroundColor: "#fff", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, maxHeight: "90%" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: "700", color: "#305797" },
  modalBody: { paddingBottom: 20 },
  modalBox: { borderWidth: 1, borderColor: "#e0e4ea", borderRadius: 12, padding: 16, marginBottom: 16, backgroundColor: "#fff" },
  calendarBox: { borderWidth: 2, borderColor: "#305797", borderRadius: 10, padding: 10, overflow: "hidden" },
  calendar: { marginTop: 8 },
  modalSubTitle: { fontSize: 14, fontWeight: "700", color: "#305797", marginBottom: 8 },
  modalParagraph: { fontSize: 13, color: "#333", marginBottom: 6 },
  modalButtonRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 14, paddingHorizontal: 16, paddingBottom: 24 },
  primaryButton: { backgroundColor: "#305797", paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, alignItems: "center", justifyContent: "center", width: '100%' },
  primaryButtonDisabled: { opacity: 0.5 },
  dangerButton: { backgroundColor: "#f3f4f6", paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, flex: 1, alignItems: "center", marginRight: 8, borderWidth: 1, borderColor: "#d1d5db" },
  primaryText: { color: "#fff", fontWeight: "600", fontSize: 14 },
  dangerText: { color: "#374151", fontWeight: "600", fontSize: 14 },
  cardOption: { borderWidth: 1, borderColor: "#e0e4ea", borderRadius: 10, padding: 10, marginBottom: 10, backgroundColor: "#f9fafc" },
  cardOptionSelected: { borderWidth: 2, borderColor: "#305797", backgroundColor: "#f0f6ff" },
  cardOptionTitle: { fontSize: 14, fontWeight: "700", color: "#305797" },
  cardOptionText: { fontSize: 12, color: "#555", marginTop: 4 },
  optionImage: { width: "100%", height: 110, borderRadius: 10, marginBottom: 6 },
  radioRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  radioOuter: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: "#305797", alignItems: "center", justifyContent: "center" },
  radioInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#305797" },
  travelerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  travelerLabel: { fontSize: 14, fontWeight: "600", color: "#333" },
  travelerSub: { fontSize: 11, color: "#777" },
  counter: { flexDirection: "row", alignItems: "center", gap: 12 },
  counterButton: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, width: 32, height: 32, alignItems: "center", justifyContent: "center", backgroundColor: "#f8fafc" },
  counterValue: { fontSize: 16, fontWeight: "700", minWidth: 20, textAlign: "center" },
  selectRow: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, padding: 8, marginBottom: 10 },
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
  checkbox: { width: 18, height: 18, borderRadius: 4, borderWidth: 1, borderColor: "#94a3b8", alignItems: "center", justifyContent: "center" },
  checkboxFill: { width: 10, height: 10, borderRadius: 2, backgroundColor: "#305797" },
  checkboxLabel: { fontSize: 13, color: "#333" },
  summaryText: { fontSize: 13, color: "#333", marginBottom: 6 },
  summaryWarning: { fontSize: 11, color: "#b91c1c", textAlign: "center", marginTop: 12 },
  termsCard: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 10, padding: 12, marginBottom: 12, backgroundColor: "#fff" },
  termsTitle: { fontSize: 15, fontWeight: "700", color: "#1f2937", marginBottom: 10 },
  termsText: { fontSize: 12, color: "#333", lineHeight: 18 },
  uploadPassportIntro: { textAlign: "center", color: "#555", marginBottom: 12, fontSize: 13 },
  uploadPassportOuter: { borderWidth: 2, borderColor: "#305797", borderRadius: 14, borderStyle: "dashed", padding: 14, marginTop: 6 },
  uploadPassportInner: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 12, borderStyle: "dashed", minHeight: 190, justifyContent: "center", alignItems: "center", paddingHorizontal: 20, paddingVertical: 20 },
  uploadPassportTitle: { marginTop: 12, fontSize: 16, color: "#222", fontWeight: "700", textAlign: "center" },
  uploadPassportHint: { marginTop: 8, fontSize: 12, color: "#777", textAlign: "center" },
  uploadPassportFileName: { marginTop: 12, fontSize: 12, color: "#305797", fontWeight: "600", textAlign: "center" },
  quotationIntro: { fontSize: 13, color: "#5b6472", lineHeight: 18, marginBottom: 12 },
  quotationRow: { flexDirection: "row", gap: 10, marginBottom: 12 },
  quotationHalf: { flex: 1 },
  quotationLabel: { fontSize: 11, fontWeight: "700", color: "#305797", marginBottom: 6 },
  quotationInput: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 14, color: "#1f2937", backgroundColor: "#fff" },
  quotationDropdownTrigger: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, backgroundColor: "#fff", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  quotationDropdownText: { color: "#1f2937", fontSize: 14, flex: 1 },
  quotationDropdownMenu: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, marginTop: 6, backgroundColor: "#fff", overflow: "hidden" },
  quotationDropdownItem: { paddingHorizontal: 12, paddingVertical: 12, borderTopWidth: 1, borderTopColor: "#e2e8f0" },
  quotationDropdownItemText: { color: "#1f2937", fontSize: 14 },
  quotationTextArea: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, minHeight: 80, color: "#1f2937", backgroundColor: "#fff", textAlignVertical: "top", marginTop: 8 },
  quotationBudgetValues: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  quotationBudgetValue: { fontSize: 14, color: "#334155", fontWeight: "600" },
  quotationItineraryCard: { backgroundColor: "#eef2f8", borderRadius: 10, padding: 16, marginBottom: 16 },
  quotationItineraryGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 12 },
  quotationItineraryItem: { width: "50%", paddingRight: 8 },
  quotationItineraryDay: { fontWeight: "700", color: "#305797", marginBottom: 4 },
  quotationNotesGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 12, columnGap: 10 },
  quotationNotesItem: { width: "48%" },
  quotationNotesItemFull: { width: "100%" },
  quotationSectionGap: { marginTop: 12, marginBottom: 4 },
  approvalCard: { alignItems: "center", padding: 20 },
  approvalIcon: { width: 60, height: 60, borderRadius: 30, backgroundColor: "#22c55e", alignItems: "center", justifyContent: "center" },
  approvalText: { marginTop: 12, fontSize: 16, fontWeight: "700", color: "#305797", textAlign: "center" },
  paymentTitle: { fontSize: 18, fontFamily: "Montserrat_700Bold", marginBottom: 20 },
  paymentSectionTitle: { fontSize: 14, fontFamily: "Montserrat_700Bold", marginTop: 20, marginBottom: 10, color: "#305797" },
  paymentCardRow: { flexDirection: "row", gap: 12 },
  paymentCard: { flex: 1, height: 80, borderRadius: 12, borderWidth: 1, borderColor: "#ddd", backgroundColor: "#fff", alignItems: "center", justifyContent: "center", elevation: 2 },
  paymentCardSelected: { borderColor: "#305797", borderWidth: 2, backgroundColor: "#F0F6FF" },
  payementCardLogo: { width: 100, height: 40, resizeMode: "contain" },
  paymentSumamryCard: { marginTop: 30, padding: 16, borderRadius: 12, backgroundColor: "#F5F8FF", borderWidth: 1, borderColor: "#305797" },
  paymentSummaryTitle: { fontFamily: "Montserrat_700Bold", fontSize: 14, color: "#305797", marginBottom: 6 },
  paymentSummaryAmount: { fontFamily: "Montserrat_700Bold", fontSize: 24, color: "#305797", marginBottom: 4 },
  paymentSummarySubtext: { fontFamily: "Roboto_400Regular", fontSize: 12, color: "#555" },
  paymentSummaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  paymentlabel: { fontFamily: "Roboto_400Regular", fontSize: 13, color: "#3b3b3b" },
  paymentValue: { fontFamily: "Montserrat_500Medium", fontSize: 13, color: "#222" },
  paymentDivider: { height: 1, backgroundColor: "#DDE3F0", marginVertical: 12 },
  wishlistContainer: { paddingHorizontal: 5, marginTop: 12 },
  wishlistButton: { backgroundColor: "#305797", paddingVertical: 12, borderRadius: 8, alignItems: "center", flexDirection: "row", justifyContent: "center" },
  wishlistButtonText: { color: "#fff", fontWeight: "600" },
  
  // 🔥 UPDATED REVIEW LIST STYLES (Blue Names & Aligned Stars) 🔥
  recentReviewContainer: { backgroundColor: "#f9fafb", padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: "#e5e7eb" },
  userReview: { fontFamily: "Montserrat_700Bold", fontSize: 14, color: "#305797", marginBottom: 2 },
  userStarContainer: { flexDirection: "row", marginTop: 2 },
  reviewHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  reviewProfileImg: { width: 40, height: 40, borderRadius: 20, marginRight: 12, backgroundColor: '#e6e9ef' },
  reviewHeaderInfo: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  
  reviewContainer: { backgroundColor: "#ffffff", padding: 20, borderRadius: 12, marginTop: 24, borderWidth: 1, borderColor: "#e5e7eb" },
  reviewTitle: { fontWeight: "700", fontSize: 16, color: "#1f2937", marginBottom: 12 },
  starsContainer: { flexDirection: "row", marginBottom: 16 },
  reviewInput: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 10, padding: 12, height: 100, textAlignVertical: "top", marginBottom: 16, backgroundColor: "#f9fafb" },
  reviewButton: { backgroundColor: "#305797", paddingVertical: 12, borderRadius: 10, alignItems: "center" },
  reviewButtonText: { color: "#fff", fontWeight: "600", fontSize: 14 },
  filterSection: { marginBottom: 20 },
  filterLabel: { fontSize: 14, fontWeight: "700", color: "#333", marginBottom: 10 },
  filterPillContainer: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  filterPill: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: "#f0f2f5", borderWidth: 1, borderColor: "#e5e7eb" },
  filterPillSelected: { backgroundColor: "#e6f4ff", borderColor: "#305797" },
  filterPillText: { fontSize: 13, color: "#555" },
  filterPillTextSelected: { color: "#305797", fontWeight: "600" },
  sliderContainer: { alignItems: "center", paddingHorizontal: 10 },
  budgetValuesRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  budgetValueText: { fontSize: 14, fontWeight: "600", color: "#305797" },
  daysValueText: { fontSize: 14, fontWeight: "600", color: "#305797", textAlign: "center", marginBottom: 10 },
  budgetInputRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingHorizontal: 10 },
  budgetInputBox: { flex: 1, borderWidth: 1, borderColor: '#dbe3ef', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: '#fff', color: '#333', fontSize: 14 },
  budgetInputText: { marginHorizontal: 15, color: '#555', fontSize: 14 },
  daysInputRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingHorizontal: 10 },
  daysInputBox: { flex: 0.8, borderWidth: 1, borderColor: '#dbe3ef', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: '#fff', color: '#333', fontSize: 14 },
  daysMaxText: { flex: 0.2, color: '#305797', fontSize: 12, fontWeight: '600', textAlign: 'center', marginLeft: 10 },
  filterSubtext: { fontSize: 11, color: '#777', marginTop: 6, marginBottom: 10, paddingHorizontal: 5 },
  arrangementModalCard: { backgroundColor: "#fff", borderRadius: 16, padding: 20, width: '92%', maxHeight: '85%', elevation: 5, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
  arrangementOptionCard: { borderWidth: 1, borderColor: "#e0e4ea", borderRadius: 12, marginBottom: 15, overflow: 'hidden', backgroundColor: "#fff" },
  arrangementOptionCardSelected: { borderColor: "#305797", borderWidth: 2, backgroundColor: "#f4f8ff" },
  arrangementImage: { width: '100%', height: 120, resizeMode: 'cover' },
  arrangementTextContainer: { padding: 12 },
  arrangementTitleText: { fontSize: 16, fontWeight: 'bold', color: '#305797', marginBottom: 6 },
  arrangementDesc: { fontSize: 12, color: '#555', lineHeight: 18 },
  arrangementNote: { fontSize: 11, color: '#d32f2f', marginTop: 8, fontStyle: 'italic', lineHeight: 16 },
  proceedButton: { backgroundColor: "#305797", paddingVertical: 12, borderRadius: 8, alignItems: "center", marginTop: 10 },
  proceedButtonText: { color: "#fff", fontWeight: "bold", fontSize: 14 },
  cancelArrangementButton: { paddingVertical: 12, alignItems: "center", marginTop: 5 },
  cancelArrangementText: { color: "#d32f2f", fontWeight: "bold", fontSize: 14 },
  dateSelectionModalCard: { backgroundColor: "#fff", borderRadius: 16, padding: 20, width: '95%', maxHeight: '85%', elevation: 5, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
  dateCard: { borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 12, padding: 16, marginBottom: 12, backgroundColor: "#fff", position: 'relative' },
  dateCardSelected: { borderColor: "#305797", borderWidth: 2, backgroundColor: "#f4f8ff" },
  dateRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  dateText: { fontSize: 14, color: "#333", marginLeft: 8, fontWeight: "500" },
  priceRowDate: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  priceTextDate: { fontSize: 14, fontWeight: "700", color: "#305797" },
  slotsBadge: { backgroundColor: "#f1f5f9", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  slotsBadgeText: { fontSize: 11, color: "#475569", fontWeight: "600" },
  selectedBadge: { position: 'absolute', top: 12, right: 12, backgroundColor: '#e6f4ff', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  selectedBadgeText: { color: '#1677ff', fontSize: 10, fontWeight: 'bold' },
  selectionFooter: { marginTop: 15, borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 15 },
  selectionFooterText: { fontSize: 13, color: '#333', marginBottom: 15 },
  selectionFooterButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  dateProceedButton: { backgroundColor: "#305797", paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8 },
  dateProceedButtonDisabled: { backgroundColor: "#94a3b8" },
  dateProceedText: { color: "#fff", fontWeight: "bold" },
  dateCancelButton: { 
    paddingHorizontal: 20, 
    paddingVertical: 10, 
    borderRadius: 8, 
    backgroundColor: '#991b1b' 
},
// 👇 Changed text color to white
dateCancelText: { 
    color: "#fff", 
    fontWeight: "bold" 
},
  
  // --- UPDATED: Review Breakdown Card Styles (BIG RATING) ---
  breakdownCard: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12, marginBottom: 20, backgroundColor: '#fff', overflow: 'hidden' },
  breakdownHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb', alignItems: 'center' },
  breakdownLabel: { fontSize: 11, color: '#777', fontFamily: 'Montserrat_600SemiBold', marginBottom: 4 },
  breakdownAvgRow: { flexDirection: 'row', alignItems: 'center', marginTop: 5, gap: 10 },
  breakdownAvgText: { fontSize: 18, fontFamily: 'Montserrat_500Medium', color: '#305797', marginRight: 10, textAlignVertical: 'center' },
  starsContainerLarge: { flexDirection: 'row', alignItems: 'center' },
  breakdownCount: { fontSize: 12, color: '#777', fontFamily: 'Roboto_400Regular' },
  breakdownBody: { padding: 16 },
  breakdownBodyTitle: { fontSize: 14, fontFamily: 'Montserrat_700Bold', color: '#1e293b', marginBottom: 12, textAlign: 'center' },
  breakdownBarRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  breakdownStarLabel: { width: 45, fontSize: 12, color: '#305797', fontFamily: 'Montserrat_600SemiBold' },
  breakdownBarBg: { flex: 1, height: 8, backgroundColor: '#e2e8f0', borderRadius: 4, marginHorizontal: 8, overflow: 'hidden' },
  breakdownBarFill: { height: '100%', backgroundColor: '#facc15', borderRadius: 4 },
  breakdownCountLabel: { width: 20, fontSize: 12, color: '#777', textAlign: 'right', fontFamily: 'Roboto_400Regular' },
});

export default DestinationStyles;