import { StyleSheet } from "react-native";

const QuotationUploadsStyle = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    container: {
        padding: 20,
    },
    notesBox: {
        backgroundColor: '#fffbe6',
        borderWidth: 1,
        borderColor: '#ffe58f',
        padding: 15,
        borderRadius: 12,
        marginBottom: 20,
    },
    notesTitle: {
        fontFamily: "Montserrat_700Bold",
        fontSize: 14,
        color: "#000000",
        marginBottom: 8,
    },
    bulletRow: {
        flexDirection: 'row',
        marginBottom: 4,
        paddingRight: 10,
    },
    bullet: {
        fontSize: 12,
        color: "#000000",
        marginRight: 6,
        lineHeight: 18,
    },
    notesText: {
        flex: 1,
        fontFamily: "Roboto_400Regular",
        fontSize: 12,
        color: "#000000",
        lineHeight: 18,
    },
    uploadCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#e7ecf7',
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
    },
    travelerHeader: {
        fontFamily: "Montserrat_700Bold",
        fontSize: 16,
        color: "#1f2a44",
        marginBottom: 4,
    },
    cardSubtitle: {
        fontFamily: "Roboto_400Regular",
        fontSize: 12,
        color: "#64748b",
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
        paddingBottom: 10,
    },
    formSection: {
        marginBottom: 16,
    },
    formRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 10,
    },
    input: {
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 13,
        fontFamily: "Roboto_400Regular",
        color: "#1f2a44",
        backgroundColor: '#fff',
    },
    selectInput: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    titleSelect: {
        flex: 0,
        width: 96,
        minHeight: 52,
    },
    inputText: {
        fontSize: 13,
        fontFamily: "Roboto_400Regular",
        color: "#1f2a44",
        flex: 1,
        textAlignVertical: 'center',
    },
    placeholderText: {
        color: '#9ca3af',
    },
    uploadRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 15,
    },
    uploadSlot: {
        flex: 1,
        alignItems: 'center',
    },
    slotLabel: {
        fontFamily: "Montserrat_600SemiBold",
        fontSize: 11,
        color: "#4e5b72",
        marginBottom: 8,
        textAlign: 'center',
        letterSpacing: 0.5
    },
    dragger: {
        width: '100%',
        aspectRatio: 1,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#305797',
        borderRadius: 12,
        backgroundColor: '#f9faff',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    draggerActive: {
        backgroundColor: '#eef3ff',
        borderStyle: 'solid',
    },
    previewImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    dropdownOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dropdownMenu: {
        width: '80%',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    dropdownItem: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    dropdownItemText: {
        fontFamily: "Roboto_500Medium",
        fontSize: 15,
        color: '#1f2a44',
    },
    iosPickerContainer: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    iosPickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
    },
    footerContainer: {
        marginTop: 10,
        paddingBottom: 50,
        paddingHorizontal: 10,
    },
    smallProceedButton: {
        backgroundColor: '#305797',
        paddingVertical: 14, 
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 15,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    smallProceedButtonText: {
        fontFamily: "Montserrat_700Bold",
        fontSize: 15, 
        color: "#ffffff",
    },
    backTextButton: {
        alignItems: 'center',
        paddingVertical: 12, 
    },
    backText: {
        fontFamily: "Montserrat_600SemiBold",
        fontSize: 15, 
        color: "#6b7486",
    }
});

export default QuotationUploadsStyle;
