import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const QuotationFormStepStyle = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#525659', 
    },
    scrollViewContent: {
        paddingVertical: 20,
        paddingBottom: 100,
    },
    paperPage: {
        backgroundColor: '#fff',
        width: width * 0.95,
        alignSelf: 'center',
        padding: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 10,
        minHeight: 800,
    },
    logo: {
        width: 180,
        height: 100,
        resizeMode: 'contain',
        alignSelf: 'center',
        marginBottom: 0,
    },
    headerGold: {
        backgroundColor: '#FFD700',
        borderWidth: 1,
        borderColor: '#000',
        paddingVertical: 5,
        alignItems: 'center',
        marginVertical: 10,
    },
    headerGoldText: {
        fontFamily: "Montserrat_700Bold",
        fontSize: 14,
        color: '#000',
    },
    headerBlue: {
        backgroundColor: '#ADD8E6',
        borderWidth: 1,
        borderColor: '#000',
        paddingVertical: 4,
        alignItems: 'center',
        marginTop: 15,
        marginBottom: 10,
    },
    headerBlueText: {
        fontFamily: "Montserrat_700Bold",
        fontSize: 12,
        color: '#000',
    },
    inputContainer: {
        marginBottom: 10,
    },
    label: {
        fontSize: 9,
        fontFamily: "Montserrat_700Bold",
        color: '#000',
        marginBottom: 2,
    },
    paperInput: {
        borderBottomWidth: 1,
        borderBottomColor: '#000',
        height: 35,
        fontSize: 11,
        paddingHorizontal: 5,
        paddingVertical: 0,
        color: '#000',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    tableWrapper: {
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#000',
    },
    tableHeaderRow: {
        flexDirection: 'row',
        backgroundColor: '#e6f7ff',
        borderBottomWidth: 1,
        borderBottomColor: '#000',
    },
    tableDataRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
    },
    columnHeader: {
        fontSize: 8,
        fontFamily: "Montserrat_700Bold",
        padding: 4,
        textAlign: 'center',
        borderRightWidth: 1,
        borderRightColor: '#000',
    },
    cellInput: {
        fontSize: 9,
        padding: 2,
        textAlign: 'center',
        borderRightWidth: 1,
        borderRightColor: '#ddd',
        height: 30,
    },
    infoBlocksRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        gap: 15,
    },
    infoBlockLeft: { flex: 1 },
    infoBlockRight: { flex: 1 },
    guideTitle: {
        fontSize: 9,
        fontFamily: "Montserrat_700Bold",
        color: '#d32f2f',
        marginBottom: 4,
    },
    guideNote: { fontSize: 7.5, fontStyle: 'italic', color: '#000', marginBottom: 4 },
    guideRow: { flexDirection: 'row', marginBottom: 4 },
    guideLabel: { fontSize: 8, fontFamily: "Montserrat_700Bold", width: 70 },
    guideDesc: { fontSize: 8, flex: 1 },
    legalText: { fontSize: 8, lineHeight: 12, marginBottom: 8, textAlign: 'justify' },
    signatureBlock: { marginTop: 30, flexDirection: 'row', justifyContent: 'space-between', gap: 20 },
    sigLine: { flex: 1, alignItems: 'center' },
    sigText: { fontSize: 9, fontFamily: 'Montserrat_700Bold', marginTop: 5 },
    modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', padding: 20 },
    verifyModalCard: {
        width: '92%',
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 22,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.18,
        shadowRadius: 12,
        elevation: 10,
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 12,
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeButtonText: {
        fontSize: 20,
        lineHeight: 22,
        color: '#8a8a8a',
        fontFamily: 'Montserrat_500Medium',
    },
    verifyModalTitle: {
        textAlign: 'center',
        fontSize: 28,
        color: '#315c9d',
        fontFamily: 'Montserrat_700Bold',
        marginTop: 4,
        marginBottom: 18,
    },
    verifyModalText: {
        textAlign: 'center',
        fontSize: 15,
        lineHeight: 22,
        color: '#4f5d74',
        fontFamily: 'Roboto_400Regular',
        marginBottom: 24,
        paddingHorizontal: 8,
    },
    verifyModalButtonsRow: {
        flexDirection: 'row',
        gap: 12,
    },
    verifyPrimaryButton: {
        flex: 1,
        backgroundColor: '#315c9d',
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        shadowColor: '#315c9d',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
    },
    verifyPrimaryButtonText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    verifySecondaryButton: {
        flex: 1,
        backgroundColor: '#a82d4d',
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        shadowColor: '#a82d4d',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
    },
    verifySecondaryButtonText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    dropdownBox: { backgroundColor: '#fff', width: 280, maxHeight: 350, borderRadius: 12, padding: 10, elevation: 5, alignSelf: 'center' },
    dropdownItem: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#f1f5f9', alignItems: 'center' },
    dropdownText: { fontFamily: 'Montserrat_700Bold', fontSize: 16, color: '#305797' },
    errorText: { color: '#d32f2f', fontFamily: 'Montserrat_600SemiBold', fontSize: 10, marginTop: 5, marginLeft: 5 },
    footerContainer: { padding: 20, paddingBottom: 40 },
    backTextButton: { alignItems: 'center', paddingVertical: 15 },
    backText: { fontFamily: 'Montserrat_600SemiBold', fontSize: 15, color: '#ccc' }
});

export default QuotationFormStepStyle;
